"""
build_database.py
-----------------
End-to-end pipeline:
  1. Read the raw Excel file and standardise it (dates, column names, whitespace)
  2. Load it into a SQLite database (staging table)
  3. Run the SQL scripts in /sql (schema -> data-quality checks -> star schema -> views)
  4. Export the star schema to /data/processed as CSVs for Power BI
  5. Save a data-quality report and the analysis query results to /docs

Usage:  python python/build_database.py
"""
import re
import sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "sales_raw.xlsx"
OUT = ROOT / "data" / "processed"
DOCS = ROOT / "docs"
SQL = ROOT / "sql"
DB = ROOT / "sales.db"

# DATA QUESTION - please confirm with the data owner:
# In the raw file every real Excel date has day <= 12 and every text date has day > 12. That split is the
# classic sign of a locale import where ambiguous dates were auto-converted, and possibly day/month swapped.
# The stored Excel dates are trusted as-is by default. Set to True to swap day and month on those cells.
SWAP_DAY_MONTH_FOR_EXCEL_DATES = False


def read_sql(name: str) -> str:
    return (SQL / name).read_text(encoding="utf-8")


def parse_date(value):
    """Raw file mixes real Excel dates and M/D/YYYY text - normalise both to a Timestamp."""
    if isinstance(value, str):
        value = value.strip()
        if "/" in value:
            return pd.to_datetime(value, format="%m/%d/%Y")   # e.g. 3/17/2026
        return pd.to_datetime(value)                          # ISO text, e.g. 2026-01-09
    ts = pd.to_datetime(value)
    if SWAP_DAY_MONTH_FOR_EXCEL_DATES:
        ts = pd.Timestamp(year=ts.year, month=ts.day, day=ts.month)
    return ts


def load_staging(conn: sqlite3.Connection) -> pd.DataFrame:
    df = pd.read_excel(RAW)
    df.columns = [re.sub(r"\W+", "_", c.strip().lower()) for c in df.columns]
    df = df.rename(columns={"date": "order_date", "discount": "discount", "revenue": "revenue"})

    # Dates first (mixed types in the raw file), then trim whitespace on the text columns
    n_text = df["order_date"].map(lambda v: isinstance(v, str)).sum()
    df["order_date"] = df["order_date"].map(parse_date).dt.strftime("%Y-%m-%d")
    for col in df.columns.drop("order_date"):
        if df[col].dtype == object or str(df[col].dtype) == "str":
            df[col] = df[col].astype(str).str.strip()
    print(f"Standardised {len(df):,} dates ({n_text:,} were text, {len(df) - n_text:,} were true dates)")

    cols = ["order_id", "order_date", "region", "sales_channel", "customer_type",
            "product_category", "product", "salesperson", "quantity", "unit_price",
            "discount", "revenue"]
    df[cols].to_sql("stg_sales", conn, if_exists="append", index=False)
    return df[cols]


def run_quality_checks(conn: sqlite3.Connection) -> pd.DataFrame:
    res = pd.read_sql_query(read_sql("02_data_quality_checks.sql"), conn)
    res["status"] = res.apply(
        lambda r: "INFO" if r.severity == "INFO" else ("PASS" if r.issues_found == 0 else "FAIL"), axis=1
    )
    print("\nData quality checks")
    print(res.to_string(index=False))
    if (res.status == "FAIL").any():
        raise SystemExit("Data-quality ERROR checks failed - fix the source data before modelling.")
    lines = ["# Data Quality Report", "",
             "| Check | Count | Severity | Status |", "|---|---:|---|---|"]
    lines += [f"| {r.check_name} | {r.issues_found:,} | {r.severity} | {r.status} |" for r in res.itertuples()]
    (DOCS / "data_quality_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return res


def export_tables(conn: sqlite3.Connection) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name in ["fact_sales", "dim_date", "dim_product", "dim_salesperson",
                 "dim_region", "dim_channel", "vw_sales_flat"]:
        df = pd.read_sql_query(f"SELECT * FROM {name}", conn)
        target = "sales_flat" if name == "vw_sales_flat" else name
        df.to_csv(OUT / f"{target}.csv", index=False)
        print(f"  exported {target}.csv  ({len(df):,} rows)")


def run_analysis(conn: sqlite3.Connection) -> None:
    """Run every '-- Q<n>' query in 05_business_analysis.sql and save results as markdown."""
    text = read_sql("05_business_analysis.sql")
    blocks = re.split(r"(?m)^-- (Q\d+: .*)$", text)[1:]
    out = ["# Analysis Query Results", "", "Generated by `python/build_database.py` from `sql/05_business_analysis.sql`.", ""]
    for title, body in zip(blocks[0::2], blocks[1::2]):
        df = pd.read_sql_query(body.strip().rstrip(";"), conn)
        for col in df.columns:  # whole-number columns print without decimals
            if pd.api.types.is_integer_dtype(df[col]) or (
                pd.api.types.is_float_dtype(df[col]) and df[col].notna().all() and (df[col] % 1 == 0).all()
            ):
                df[col] = df[col].astype("int64")
        out += [f"## {title}", "", df.astype(object).to_markdown(index=False, floatfmt=",.2f", intfmt=","), ""]
    (DOCS / "analysis_results.md").write_text("\n".join(out), encoding="utf-8")
    print(f"\nSaved {len(blocks)//2} analysis results to docs/analysis_results.md")


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    if DB.exists():
        DB.unlink()
    conn = sqlite3.connect(DB)
    conn.executescript(read_sql("01_schema.sql"))
    load_staging(conn)
    run_quality_checks(conn)
    conn.executescript(read_sql("03_build_star_schema.sql"))
    conn.executescript(read_sql("04_views.sql"))
    conn.commit()

    fact_rows = conn.execute("SELECT COUNT(*) FROM fact_sales").fetchone()[0]
    stg_rows = conn.execute("SELECT COUNT(*) FROM stg_sales").fetchone()[0]
    assert fact_rows == stg_rows, f"Row mismatch: staging {stg_rows} vs fact {fact_rows}"
    print(f"\nStar schema built - fact_sales has {fact_rows:,} rows (matches staging)")

    export_tables(conn)
    run_analysis(conn)
    conn.close()
    print("\nDone. Open Power BI Desktop and import the CSVs in data/processed/.")


if __name__ == "__main__":
    main()
